FROM alpine:3

LABEL author="Bobby Akyong"
LABEL websiteauthor="https://www.bobbyakyong.com"
LABEL company="PT Qeong Mas Indonesia" website="https://www.qeong.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"